// macros for custom hemispheres configurations
#ifdef ENABLE_HEM_ADSREG
    #define DECLARE_HEM_ADSREG DECLARE_APPLET(  8, 0x01, ADSREG),
#else
    #define DECLARE_HEM_ADSREG
#endif

#ifdef ENABLE_HEM_ADEG
    #define DECLARE_HEM_ADEG DECLARE_APPLET( 34, 0x01, ADEG),
#else
    #define DECLARE_HEM_ADEG
#endif

#ifdef ENABLE_HEM_ASR
    #define DECLARE_HEM_ASR DECLARE_APPLET( 47, 0x09, ASR),
#else
    #define DECLARE_HEM_ASR
#endif

#ifdef ENABLE_HEM_ATTENUATEOFFSET
    #define DECLARE_HEM_ATTENUATEOFFSET DECLARE_APPLET( 56, 0x10, AttenuateOffset),
#else
    #define DECLARE_HEM_ATTENUATEOFFSET
#endif

#ifdef ENABLE_HEM_BINARY
    #define DECLARE_HEM_BINARY DECLARE_APPLET( 41, 0x41, Binary),
#else
    #define DECLARE_HEM_BINARY
#endif

#ifdef ENABLE_HEM_BOOTSNCAT
    #define DECLARE_HEM_BOOTSNCAT DECLARE_APPLET( 55, 0x80, BootsNCat),
#else
    #define DECLARE_HEM_BOOTSNCAT
#endif

#ifdef ENABLE_HEM_BOWTIESEQ
    #define DECLARE_HEM_BOWTIESEQ DECLARE_APPLET( 38, 0x80, BowTieSeq),
#else
    #define DECLARE_HEM_BOWTIESEQ
#endif

#ifdef ENABLE_HEM_BRANCHER
    #define DECLARE_HEM_BRANCHER DECLARE_APPLET(  4, 0x14, Brancher),
#else
    #define DECLARE_HEM_BRANCHER
#endif

#ifdef ENABLE_HEM_BUGCRACK
    #define DECLARE_HEM_BUGCRACK DECLARE_APPLET( 51, 0x80, BugCrack),
#else
    #define DECLARE_HEM_BUGCRACK
#endif

#ifdef ENABLE_HEM_BURST
    #define DECLARE_HEM_BURST DECLARE_APPLET( 31, 0x04, Burst),
#else
    #define DECLARE_HEM_BURST
#endif

#ifdef ENABLE_HEM_BUTTON
    #define DECLARE_HEM_BUTTON DECLARE_APPLET( 65, 0x10, Button),
#else
    #define DECLARE_HEM_BUTTON
#endif

#ifdef ENABLE_HEM_CALCULATE
    #define DECLARE_HEM_CALCULATE DECLARE_APPLET( 12, 0x10, Calculate),
#else
    #define DECLARE_HEM_CALCULATE
#endif

#ifdef ENABLE_HEM_CALIBR8
    #define DECLARE_HEM_CALIBR8 DECLARE_APPLET( 88, 0x10, Calibr8),
#else
    #define DECLARE_HEM_CALIBR8
#endif

#ifdef ENABLE_HEM_CARPEGGIO
    #define DECLARE_HEM_CARPEGGIO DECLARE_APPLET( 32, 0x0a, Carpeggio),
#else
    #define DECLARE_HEM_CARPEGGIO
#endif

#ifdef ENABLE_HEM_CHORDINATOR
    #define DECLARE_HEM_CHORDINATOR DECLARE_APPLET( 64, 0x08, Chordinator),
#else
    #define DECLARE_HEM_CHORDINATOR
#endif

#ifdef ENABLE_HEM_CLOCKDIVIDER
    #define DECLARE_HEM_CLOCKDIVIDER DECLARE_APPLET(  6, 0x04, ClockDivider),
#else
    #define DECLARE_HEM_CLOCKDIVIDER
#endif

#ifdef ENABLE_HEM_CLOCKSKIP
    #define DECLARE_HEM_CLOCKSKIP DECLARE_APPLET( 28, 0x04, ClockSkip),
#else
    #define DECLARE_HEM_CLOCKSKIP
#endif

#ifdef ENABLE_HEM_COMPARE
    #define DECLARE_HEM_COMPARE DECLARE_APPLET( 30, 0x10, Compare),
#else
    #define DECLARE_HEM_COMPARE
#endif

#ifdef ENABLE_HEM_CVRECV2
    #define DECLARE_HEM_CVRECV2 DECLARE_APPLET( 24, 0x02, CVRecV2),
#else
    #define DECLARE_HEM_CVRECV2
#endif

#ifdef ENABLE_HEM_DRCRUSHER
    #define DECLARE_HEM_DRCRUSHER DECLARE_APPLET( 63, 0x80, DrCrusher),
#else
    #define DECLARE_HEM_DRCRUSHER
#endif

#ifdef ENABLE_HEM_DRUMMAP
    #define DECLARE_HEM_DRUMMAP DECLARE_APPLET( 57, 0x02, DrumMap),
#else
    #define DECLARE_HEM_DRUMMAP
#endif

#ifdef ENABLE_HEM_DUALQUANT
    #define DECLARE_HEM_DUALQUANT DECLARE_APPLET(  9, 0x08, DualQuant),
#else
    #define DECLARE_HEM_DUALQUANT
#endif

#ifdef ENABLE_HEM_DUALTM
    #define DECLARE_HEM_DUALTM DECLARE_APPLET( 18, 0x02, DualTM),
#else
    #define DECLARE_HEM_DUALTM
#endif

#ifdef ENABLE_HEM_EBBANDLFO
    #define DECLARE_HEM_EBBANDLFO DECLARE_APPLET(  7, 0x01, EbbAndLfo),
#else
    #define DECLARE_HEM_EBBANDLFO
#endif

#ifdef ENABLE_HEM_ENIGMAJR
    #define DECLARE_HEM_ENIGMAJR DECLARE_APPLET( 45, 0x02, EnigmaJr),
#else
    #define DECLARE_HEM_ENIGMAJR
#endif

#ifdef ENABLE_HEM_ENVFOLLOW
    #define DECLARE_HEM_ENVFOLLOW DECLARE_APPLET( 42, 0x11, EnvFollow),
#else
    #define DECLARE_HEM_ENVFOLLOW
#endif

#ifdef ENABLE_HEM_EUCLIDX
    #define DECLARE_HEM_EUCLIDX DECLARE_APPLET( 15, 0x02, EuclidX),
#else
    #define DECLARE_HEM_EUCLIDX
#endif

#ifdef ENABLE_HEM_GAMEOFLIFE
    #define DECLARE_HEM_GAMEOFLIFE DECLARE_APPLET( 22, 0x01, GameOfLife),
#else
    #define DECLARE_HEM_GAMEOFLIFE
#endif

#ifdef ENABLE_HEM_GATEDELAY
    #define DECLARE_HEM_GATEDELAY DECLARE_APPLET( 29, 0x04, GateDelay),
#else
    #define DECLARE_HEM_GATEDELAY
#endif

#ifdef ENABLE_HEM_GATEDVCA
    #define DECLARE_HEM_GATEDVCA DECLARE_APPLET( 17, 0x50, GatedVCA),
#else
    #define DECLARE_HEM_GATEDVCA
#endif

#ifdef ENABLE_HEM_LOFIPCM
    #define DECLARE_HEM_LOFIPCM DECLARE_APPLET( 16, 0x80, LoFiPCM),
#else
    #define DECLARE_HEM_LOFIPCM
#endif

#ifdef ENABLE_HEM_LOGIC
    #define DECLARE_HEM_LOGIC DECLARE_APPLET( 10, 0x44, Logic),
#else
    #define DECLARE_HEM_LOGIC
#endif

#ifdef ENABLE_HEM_LOWERRENZ
    #define DECLARE_HEM_LOWERRENZ DECLARE_APPLET( 21, 0x01, LowerRenz),
#else
    #define DECLARE_HEM_LOWERRENZ
#endif

#ifdef ENABLE_HEM_METRONOME
    #define DECLARE_HEM_METRONOME DECLARE_APPLET( 50, 0x04, Metronome),
#else
    #define DECLARE_HEM_METRONOME
#endif

#ifdef ENABLE_HEM_HMIDIIN
    #define DECLARE_HEM_HMIDIIN DECLARE_APPLET(150, 0x20, hMIDIIn),
#else
    #define DECLARE_HEM_HMIDIIN
#endif

#ifdef ENABLE_HEM_HMIDIOUT
    #define DECLARE_HEM_HMIDIOUT DECLARE_APPLET( 27, 0x20, hMIDIOut),
#else
    #define DECLARE_HEM_HMIDIOUT
#endif

#ifdef ENABLE_HEM_MIXERBAL
    #define DECLARE_HEM_MIXERBAL DECLARE_APPLET( 33, 0x10, MixerBal),
#else
    #define DECLARE_HEM_MIXERBAL
#endif

#ifdef ENABLE_HEM_PALIMPSEST
    #define DECLARE_HEM_PALIMPSEST DECLARE_APPLET( 20, 0x02, Palimpsest),
#else
    #define DECLARE_HEM_PALIMPSEST
#endif

#ifdef ENABLE_HEM_PROBABILITYDIVIDER
    #define DECLARE_HEM_PROBABILITYDIVIDER DECLARE_APPLET( 59, 0x04, ProbabilityDivider),
#else
    #define DECLARE_HEM_PROBABILITYDIVIDER
#endif

#ifdef ENABLE_HEM_PROBABILITYMELODY
    #define DECLARE_HEM_PROBABILITYMELODY DECLARE_APPLET( 62, 0x04, ProbabilityMelody),
#else
    #define DECLARE_HEM_PROBABILITYMELODY
#endif

#ifdef ENABLE_HEM_RNDWALK
    #define DECLARE_HEM_RNDWALK DECLARE_APPLET( 69, 0x01, RndWalk),
#else
    #define DECLARE_HEM_RNDWALK
#endif

#ifdef ENABLE_HEM_RUNGLEBOOK
    #define DECLARE_HEM_RUNGLEBOOK DECLARE_APPLET( 44, 0x01, RunglBook),
#else
    #define DECLARE_HEM_RUNGLEBOOK
#endif

#ifdef ENABLE_HEM_SAMPLEANDHOLD
    #define DECLARE_HEM_SAMPLEANDHOLD DECLARE_APPLET( 1, 0x10, SampleAndHold),
#else
    #define DECLARE_HEM_SAMPLEANDHOLD
#endif

#ifdef ENABLE_HEM_SCALEDUET
    #define DECLARE_HEM_SCALEDUET DECLARE_APPLET( 26, 0x08, ScaleDuet),
#else
    #define DECLARE_HEM_SCALEDUET
#endif

#ifdef ENABLE_HEM_SCHMITT
    #define DECLARE_HEM_SCHMITT DECLARE_APPLET( 40, 0x40, Schmitt),
#else
    #define DECLARE_HEM_SCHMITT
#endif

#ifdef ENABLE_HEM_SCOPE
    #define DECLARE_HEM_SCOPE DECLARE_APPLET( 23, 0x80, Scope),
#else
    #define DECLARE_HEM_SCOPE
#endif

#ifdef ENABLE_HEM_SEQUENCEX
    #define DECLARE_HEM_SEQUENCEX DECLARE_APPLET( 14, 0x02, SequenceX),
#else
    #define DECLARE_HEM_SEQUENCEX
#endif

#ifdef ENABLE_HEM_SHIFTGATE
    #define DECLARE_HEM_SHIFTGATE DECLARE_APPLET( 48, 0x45, ShiftGate),
#else
    #define DECLARE_HEM_SHIFTGATE
#endif

#ifdef ENABLE_HEM_SHREDDER
    #define DECLARE_HEM_SHREDDER DECLARE_APPLET( 58, 0x01, Shredder),
#else
    #define DECLARE_HEM_SHREDDER
#endif

#ifdef ENABLE_HEM_SHUFFLE
    #define DECLARE_HEM_SHUFFLE DECLARE_APPLET( 36, 0x04, Shuffle),
#else
    #define DECLARE_HEM_SHUFFLE
#endif

#ifdef ENABLE_HEM_SLEW
    #define DECLARE_HEM_SLEW DECLARE_APPLET( 19, 0x01, Slew),
#else
    #define DECLARE_HEM_SLEW
#endif

#ifdef ENABLE_HEM_SQUANCH
    #define DECLARE_HEM_SQUANCH DECLARE_APPLET( 46, 0x08, Squanch),
#else
    #define DECLARE_HEM_SQUANCH
#endif

#ifdef ENABLE_HEM_STAIRS
    #define DECLARE_HEM_STAIRS DECLARE_APPLET( 61, 0x01, Stairs),
#else
    #define DECLARE_HEM_STAIRS
#endif

#ifdef ENABLE_HEM_SWITCH
    #define DECLARE_HEM_SWITCH DECLARE_APPLET(  3, 0x10, Switch),
#else
    #define DECLARE_HEM_SWITCH
#endif

#ifdef ENABLE_HEM_TB3PO
    #define DECLARE_HEM_TB3PO DECLARE_APPLET( 60, 0x02, TB_3PO),
#else
    #define DECLARE_HEM_TB3PO
#endif

#ifdef ENABLE_HEM_TLNEURON
    #define DECLARE_HEM_TLNEURON DECLARE_APPLET( 13, 0x40, TLNeuron),
#else
    #define DECLARE_HEM_TLNEURON
#endif

#ifdef ENABLE_HEM_TRENDING
    #define DECLARE_HEM_TRENDING DECLARE_APPLET( 37, 0x40, Trending),
#else
    #define DECLARE_HEM_TRENDING
#endif

#ifdef ENABLE_HEM_TRIGSEQ
    #define DECLARE_HEM_TRIGSEQ DECLARE_APPLET( 11, 0x06, TrigSeq),
#else
    #define DECLARE_HEM_TRIGSEQ
#endif

#ifdef ENABLE_HEM_TRIGSEQ16
    #define DECLARE_HEM_TRIGSEQ16 DECLARE_APPLET( 25, 0x06, TrigSeq16),
#else
    #define DECLARE_HEM_TRIGSEQ16
#endif

#ifdef ENABLE_HEM_TUNER
    #define DECLARE_HEM_TUNER DECLARE_APPLET( 39, 0x80, Tuner),
#else
    #define DECLARE_HEM_TUNER
#endif

#ifdef ENABLE_HEM_VECTOREG
    #define DECLARE_HEM_VECTOREG DECLARE_APPLET( 52, 0x01, VectorEG),
#else
    #define DECLARE_HEM_VECTOREG
#endif

#ifdef ENABLE_HEM_VECTORLFO
    #define DECLARE_HEM_VECTORLFO DECLARE_APPLET( 49, 0x01, VectorLFO),
#else
    #define DECLARE_HEM_VECTORLFO
#endif

#ifdef ENABLE_HEM_VECTORMOD
    #define DECLARE_HEM_VECTORMOD DECLARE_APPLET( 53, 0x01, VectorMod),
#else
    #define DECLARE_HEM_VECTORMOD
#endif

#ifdef ENABLE_HEM_VECTORMORPH
    #define DECLARE_HEM_VECTORMORPH DECLARE_APPLET( 54, 0x01, VectorMorph),
#else
    #define DECLARE_HEM_VECTORMORPH
#endif

#ifdef ENABLE_HEM_VOLTAGE
    #define DECLARE_HEM_VOLTAGE DECLARE_APPLET( 43, 0x10, Voltage),
#else
    #define DECLARE_HEM_VOLTAGE
#endif

#define HEMISPHERE_APPLETS { \
    DECLARE_HEM_ADSREG \
    DECLARE_HEM_ADEG \
    DECLARE_HEM_ASR \
    DECLARE_HEM_ATTENUATEOFFSET \
    DECLARE_HEM_BINARY \
    DECLARE_HEM_BOOTSNCAT \
    DECLARE_HEM_BOWTIESEQ \
    DECLARE_HEM_BRANCHER \
    DECLARE_HEM_BUGCRACK \
    DECLARE_HEM_BURST \
    DECLARE_HEM_BUTTON \
    DECLARE_HEM_CALCULATE \
    DECLARE_HEM_CALIBR8 \
    DECLARE_HEM_CARPEGGIO \
    DECLARE_HEM_CHORDINATOR \
    DECLARE_HEM_CLOCKDIVIDER \
    DECLARE_HEM_CLOCKSKIP \
    DECLARE_HEM_COMPARE \
    DECLARE_HEM_CVRECV2 \
    DECLARE_HEM_DRCRUSHER \
    DECLARE_HEM_DRUMMAP \
    DECLARE_HEM_DUALQUANT \
    DECLARE_HEM_DUALTM \
    DECLARE_HEM_EBBANDLFO \
    DECLARE_HEM_ENIGMAJR \
    DECLARE_HEM_ENVFOLLOW \
    DECLARE_HEM_EUCLIDX \
    DECLARE_HEM_GAMEOFLIFE \
    DECLARE_HEM_GATEDELAY \
    DECLARE_HEM_GATEDVCA \
    DECLARE_HEM_LOFIPCM \
    DECLARE_HEM_LOGIC \
    DECLARE_HEM_LOWERRENZ \
    DECLARE_HEM_METRONOME \
    DECLARE_HEM_HMIDIIN \
    DECLARE_HEM_HMIDIOUT \
    DECLARE_HEM_MIXERBAL \
    DECLARE_HEM_PALIMPSEST \
    DECLARE_HEM_PROBABILITYDIVIDER \
    DECLARE_HEM_PROBABILITYMELODY \
    DECLARE_HEM_RNDWALK \
    DECLARE_HEM_RUNGLEBOOK \
    DECLARE_HEM_SAMPLEANDHOLD \
    DECLARE_HEM_SCALEDUET \
    DECLARE_HEM_SCHMITT \
    DECLARE_HEM_SCOPE \
    DECLARE_HEM_SEQUENCEX \
    DECLARE_HEM_SHIFTGATE \
    DECLARE_HEM_SHREDDER \
    DECLARE_HEM_SHUFFLE \
    DECLARE_HEM_SLEW \
    DECLARE_HEM_SQUANCH \
    DECLARE_HEM_STAIRS \
    DECLARE_HEM_SWITCH \
    DECLARE_HEM_TB3PO \
    DECLARE_HEM_TLNEURON \
    DECLARE_HEM_TRENDING \
    DECLARE_HEM_TRIGSEQ \
    DECLARE_HEM_TRIGSEQ16 \
    DECLARE_HEM_TUNER \
    DECLARE_HEM_VECTOREG \
    DECLARE_HEM_VECTORLFO \
    DECLARE_HEM_VECTORMOD \
    DECLARE_HEM_VECTORMORPH \
    DECLARE_HEM_VOLTAGE \
}
